[platformio]
src_dir = firmware
data_dir = firmware/data
build_dir = D:/rn-cache/module_robot_pio_build

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
  adafruit/Adafruit BNO08x
