#pragma once

#define RTK_ROUTER_WIFI_SSID "YOUR_2G_WIFI_SSID"
#define RTK_ROUTER_WIFI_PASS "YOUR_WIFI_PASSWORD"

#define RTK_ROVER_IP_A 192
#define RTK_ROVER_IP_B 168
#define RTK_ROVER_IP_C 31
#define RTK_ROVER_IP_D 222

#define RTK_BASE_IP_A 192
#define RTK_BASE_IP_B 168
#define RTK_BASE_IP_C 31
#define RTK_BASE_IP_D 207

#define RTK_ROUTER_GATEWAY_A 192
#define RTK_ROUTER_GATEWAY_B 168
#define RTK_ROUTER_GATEWAY_C 31
#define RTK_ROUTER_GATEWAY_D 1
