[platformio]
test_dir = test
build_dir = ../.pio/build_navigation_core

[env:native]
platform = native
test_framework = googletest
extra_scripts = pre:pio_native_toolchain.py
build_flags =
  -std=c++17
  -Wall
  -Wextra
  -I .
