[platformio]
src_dir = src
build_dir = D:/rn-cache/module_rtk_pio_build

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:base]
build_src_filter =
  +<base.cpp>
  -<rover.cpp>

[env:rover]
build_src_filter =
  +<rover.cpp>
  -<base.cpp>
lib_deps =
  ESP32Async/AsyncTCP
  ESP32Async/ESPAsyncWebServer
